services:
  - type: web
    name: artlist-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn core.wsgi:application --bind 0.0.0.0:$PORT --workers 3
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DB_NAME
        value: artlist
      - key: DB_USER
        value: artlist_user
      - key: DB_PASSWORD
        value: artlist_pass
      - key: DB_HOST
        fromService:
          name: artlist-db
          type: pserv
          property: host
      - key: DB_PORT
        value: 5432
      - key: TMDB_API_KEY
        sync: false

databases:
  - name: artlist-db
    plan: free